import React, {Component} from 'react'
import Card from './CardUI';
/* import axios from 'axios';
import App from './App';*/

import btc from '../assets/bitcoin.jpeg';
import eth from '../assets/ether.png';
import ltc from '../assets/ltc.jpeg';
import xrp from '../assets/xrp.png';

class Cards extends Component{
    render(){
        return (
            <div className="container-fluid d-flex justify-center">
                <div className="row">
                    <div className="col-md-4">
                        <Card imgsrc={btc}title='Bitcoin' body="Bitcoin (BTC) is the best-known cryptocurrency, the one for which blockchain technology was invented. It has been the inspiration for many other blockchains that exist now."/>
                    </div>
                    <div className="col-md-4">
                        <Card imgsrc={eth}title='Ether' body='Ether (ETH) is the cryptocurrency generated by Ethereum miners as a reward for computations performed to secure and add blocks to the blockchain.'/>
                    </div>
                    <div className="col-md-4"> 
                        <Card imgsrc={ltc}title='LiteCoin'body="Litecoin (LTC) is a peer-to-peer internet currency. It is a fully decentralized open source, global payment network. Litecoin has earned industry support along with high trade volume and liquidity over the years."/>
                    </div>
                    <div className="col-md-4">
                        <Card imgsrc={xrp}title='Ripple'body="Ripple (XRP) is a real-time gross settlement system, currency exchange and remittance network created by Ripple Labs Inc. XRP was recently named the third largest coin by Market Capitalization."/>
                    </div>
                </div>
            </div>
        )
    }
}
export default Cards;